# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: /images/favicon.ico

version: 2

# Personal info
name: Jinwan Seo
title: Web Service Developer
email: jinwanseo@gmail.com
phone: 010-8888-6306
website: https://jinwanseo.site
darkmode: true

github_username: jinwanseo

instagram_username: roimemory

additional_links:
  - title: Tistory
    icon: fas fa-blog
    url: https://goodmemory.tistory.com/

about_profile_image: /images/profile.jpg
about_content: |
  Java & Spring / TypeScript & NestJS / Python & FastAPI / React / AWS 기반의 3년차 웹 서비스 개발자로 
  **우리카드, 한샘 등 다양한 기업의 RPA 웹 포탈 서비스를 구축**해왔고, 현재는 **KB 라이프의 (POC) AI 기반의 문서 이미지 OCR, 챗봇 서비스 및 NLP 모듈 개발 중**에 있습니다.
  
  진정한 웹 서비스 개발자는 포지션에 큰 의미를 두지 않고 <mark>프로젝트에 도움이 되는 역할</mark>을 해야한다는 생각에 HTML/CSS 부터 JENKINS CI/CD 까지 다양한 업무를 경계없이 수행하였습니다.
  이러한 경험을 통해 어떤 포지션이든 <mark>즉시 전력이 될 준비</mark>가 되어있으며 동료들의 긴급한 휴가 또는 부재시 빈 자리를 채워줄 수 있습니다.
  
  현재는 (주) 레인보우 브레인에서 근무중이며 <mark>백엔드 개발</mark>을 주로 하고 있습니다.


content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 레인보우 브레인
        sub_title: 책임 연구원
        link: https://rbrain.co.kr
        link_text: https://rbrain.co.kr
        caption: 2021.08 - 현재

        description: |
          - 우리카드, 한샘 웹 포탈 서비스 프론트 부분 아키텍처 설계 및 개발
          - KB 라이프 POC AI 기반의 문서 이미지 OCR, NLP 모듈 개발
          - AWS EC2, S3 등을 이용한 서비스 배포 및 운영
          - Jenkins CI/CD 파이프라인 구축
          - 애자일 환경에서의 개발 및 코드 리뷰

      - layout: left
        title: 컴세바 IT 학원
        sub_title: C/C++ 강사
        link: http://comseba.co.kr
        link_text: http://comseba.co.kr
        caption: 2018.01 - 2018.08

        description: |
          - C/C++ 언어 기초부터 심화까지 강의
          - 프로젝트 지도 및 피드백
          - 학습 효율을 높이기 위한 교육 방법론 개발
          - 학습 상황을 파악하기 위한 테스트 및 퀴즈 작성

  - title: Skill
    layout: list
    content:
      - layout: left
        title: Backend
        description: |
          - Spring & Java (Gradle, JPA)
          - NestJS & TypeScript (TypeORM)
          - FastAPI & Python (SQLAlchemy)
          - IntelliJ IDEA / VSCode / PyCharm


      - layout: left
        title: DevOps
        description: |
          - PostgreSQL, MongoDB, Redis, RabbitMQ
          - Docker, Jenkins
          - AWS (EC2, S3)
          - Ubuntu, MacOS

      - layout: left
        title: Frontend
        description: |
          - React & Native & TypeScript
          - Material-UI, Tailwind CSS
          - Npm, Webpack
          - IntelliJ WebStorm / VSCode

  - title: Projects
    layout: list
    content:
      - layout: left
        title: 우리카드
        sub_title: RPA 웹 포탈 서비스
        description: |
          - 금융권 보안 정책 준수를 위한 보안 코드 작성 및 외부 모듈 사용 최소화
          - Webpack & ES6 만을 사용하여 웹 퍼블리셔와 함께 웹 서비스 개발
          - 디자인 협업툴 Figma 를 사용하여 디자이너와의 원활한 소통읉 통해 디자인 시안을 빠르게 반영

      - layout: left
        title: 한샘
        sub_title: RPA 웹 포탈 서비스
        description: |
          - React & MUI 기반의 프론트엔드 아키텍처 설계 및 개발
          - Spring 기반의 백엔드 개발자의 퇴사에 따른 백엔드 개발 업무 수행
          - Jenkins CI/CD 파이프라인 구축 및 운영

      - layout: left
        title: 스탠바이투게더
        sub_title: 스마트 대기 플랫폼
        description: |
          - NestJS & TypeScript 기반의 백엔드 개발
          - React & TailwindCSS 기반의 프론트 개발
          - AWS (EC2, S3) 를 이용한 서비스 배포

      - layout: left
        title: AI Scheduler
        sub_title: 스케쥴러 모듈
        description: |
          - Java & Spring 기반의 백엔드 개발
          - RabbitMQ 기반의 스케쥴러 모듈 개발
          - Python 기반의 Job Worker 및 DALLE-3 기반 이미지 생성 모듈 개발

      - layout: left
        title: KB 손해보험 POC
        sub_title: AI 모듈
        description: |
          - FastAPI 기반의 백엔드 개발 지원
          - PDF 문서, 이미지 파일 OCR 모듈 개발 
          - ChatBot 서비스를 위한 NLP 모듈 개발

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Seoul High School
        sub_title: 문과 (졸업)
        caption: 2003.03 - 2006.02

      - layout: top-middle
        title: SeoKyung University
        sub_title: 경영학과 3.52 / 4.50 (졸업)
        caption: 2009.03 - 2015.02

      - layout: top-middle
        title: Fullstack Course
        sub_title: NestJS & React & TypeScript Course (수료)
        caption: 2022.10 - 2023.04

      - layout: top-middle
        title: Application Course
        sub_title: Flutter & Dart Developer Course (수료)
        caption: 2023.01 - 2015.04

      - layout: top-middle
        title: Spring Boot Course
        sub_title: 배달의 민족 김영한 Spring 완전 정복 코스 (수료)
        caption: 2023.04 - 2023.10

      - layout: top-middle
        title: Spring JPA Course
        sub_title: 배달의 민족 김영한 JPA 완전 정복 코스 (수료)
        caption: 2023.10 - 2024.01

  - title: Philosophy
    layout: list
    content:
      - layout: left
        title: 정말 서비스에 대해<br/>잘 이해하고 있는가?
        description: |
          웹 개발자로서 구현할 서비스의 비즈니스 모델을 깊이 이해하는 것이 핵심이라고 생각합니다.<br/>
          여기서 이해란 교육을 통한 제품이나 서비스의 장단점에 대한 부분을 넘어 **소비자로서의 경험을 통한 심층적인 이해**를 의미합니다. 저는 서비스를 개발 하기 전 이러한 부분을 항상 먼저 고민합니다.

      - layout: right
        title: 개발자는 개발만<br/> 잘 하면 되는가?
        description: |
          웹 개발은 사용자와의 사업자간의 접점을 만들어내는 일이기 때문에 유연한 사고가 개발 능력 만큼 중요하다고 생각합니다.
          만약 갑작스러운 인력의 부재로 개발 인력은 물론, 개발과 관련이 없는 영업 인력의 부재라도 회사와 프로젝트에 도움이될 수 있다면 언제든지 채울 수 있는 마음가짐이 되어있습니다.  


#  - title: Certificate
#    layout: text
#    content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
